services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: lightit_laravel
        container_name: laravel.test
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - mysql
            - nginx
        volumes:
            - './:/var/www'
        networks:
            - laravel-network
    nginx:
        image: 'nginx:alpine'
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - './:/var/www'
            - './docker-compose/nginx:/etc/nginx/conf.d/'
        networks:
            - laravel-network
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - laravel-network
        ports:
            - '3306:3306'
networks:
    laravel-network:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
